---
title: "Piano Assignment - R"
author: "Shahrar Nizam"
date: "6/11/2021"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
```{r}
library(dplyr)
library(httr)
library(jsonlite)
```
```{r}
#Read FileA and FileB and join on userid
fileA<- read.csv("/Users/shahrarnizam/Documents/Piano/FileA.csv" , head(T))
fileB<-read.csv("/Users/shahrarnizam/Documents/Piano/FileB.csv" , head(T))
merged <- merge(fileA,fileB,by=c('user_id'),all.x=T)
```
```{r}
merged
```
```{r}

#Get API usernames
res = GET("https://sandbox.piano.io/api/v3/publisher/user/list",
          query = list(aid="o1sRRZSLlw", api_token="zziNT81wShznajW2BD5eLA4VCkmNJ88Guye7Sw4D",
                       limit=100, offset=0))
data = fromJSON(rawToChar(res$content))

data
```
```{r}
#Convert both lists to dataframes
outdata <- data.frame(merged)
apidata <- data.frame(data)

#Convert factor dataframe to character
outdata <- data.frame(lapply(outdata, as.character), stringsAsFactors=FALSE)

#Update userid in output file
outdata$user_id[3]<-apidata$users.uid[3]
outdata$user_id[4]<-apidata$users.uid[4]
outdata$user_id[5]<-apidata$users.uid[5]
outdata
```
```{r}
#Export output file
write.csv(outdata,"/Users/shahrarnizam/Documents/Piano/FileCR.csv" , all(T) )
```

